[main]
font=CaskaydiaMono Nerd Font:size=08
dpi-aware=auto
prompt="🔎 "
icon-theme=Papirus-Dark
icons-enabled=yes
lines=10
width=40
horizontal-pad=20
vertical-pad=10
inner-pad=5

[colors]
# Tokyo Night
background=1a1b26ee
text=c0caf5ff
selection=33467cff
selection-text=c0caf5ff
selection-match=ff9e64ff
border=7aa2f7ff
match=9ece6aff

[border]
width=2
radius=2

[key-bindings]
prev=Up Control+p Control+k
next=Down Control+n Control+j
